//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostoGasolina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemServico
    {
        public int id { get; set; }
        public Nullable<double> ValorLitro { get; set; }
        public Nullable<System.DateTime> DataOrdem { get; set; }
        public Nullable<double> QtdCombustivel { get; set; }
        public Nullable<int> IdMotorista { get; set; }
        public Nullable<int> idPosto { get; set; }
    
        public virtual Motorista Motorista { get; set; }
        public virtual Posto Posto { get; set; }
    }
}
