//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostoGasolina.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculo
    {
        public int id { get; set; }
        public string Marca { get; set; }
        public Nullable<int> TipoCombustivel { get; set; }
        public Nullable<int> Motorista { get; set; }
    
        public virtual Motorista Motorista1 { get; set; }
        public virtual TipoCombustivel TipoCombustivel1 { get; set; }
    }
}
